project:
  type: book

book:
  title: "Land-Atmosphere Interactions: Practicals"
  subtitle: "Academic year: 2025 - 2026"
  author: 
    name: Olivier Bonte
    affiliation: Ghent University
    email: olivier.bonte@ugent.be
  date: today
  chapters:
    - index.qmd
    - practical_1.qmd
    - practical_2.qmd
    - references.qmd
  downloads: [pdf]
  repo-url: https://github.com/h-cel/land-atmosphere-interactions-public
  navbar: 
    title: "Land-Atmosphere Interactions: Practicals"
    search: true 
    logo: "figures/logo_H-CEL_no_background.svg"

bibliography: references.bib
jupyter: python3

format:
  html:
    theme: cosmo
    code-overflow: wrap
    code-fold: show
  pdf:
    documentclass: scrreprt
    include-in-header: preamble.tex
        
# Allows caching of notebooks when previewing 
execute:
  cache: true
  freeze: auto


